<?php

namespace emeraldinspirations\TaskListDemo\task;
include "../src/task/cliView.php";
include "../src/task/taskModel.php";

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-03 at 04:25:12.
 */
class cliViewTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var cliView
   */
  protected $object;
  
  /**
   *
   * @var taskModel
   */
  protected $SampleTask;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    
    //$this->object = new cliView;
    
    $this->SampleTask = new taskModel();
    $this->SampleTask->UpdatedDate = '2016-09-03 04:45:21';
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * @covers emeraldinspirations\TaskListDemo\task\cliView::output
   * @todo   Implement testOutput().
   */
  public function testOutput() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers emeraldinspirations\TaskListDemo\task\cliView::renderModDate
   * @todo   Implement testRenderModDate().
   */
  public function testRenderModDate() {
    $this->assertEquals(
            "\033[36m2016-09-03",
            cliView::renderModDate($this->SampleTask),
            'Modified Date not rendered correctly'
    );
  }

}
