<?php

namespace SnSDev\TaskListDemo\task;
include "../src/task/cliListView.php";
include "../src/task/taskModel.php";

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-03 at 04:25:12.
 */
class cliListViewTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var cliListView
   */
  protected $object;
  
  /**
   *
   * @var taskModel
   */
  protected $SampleTask;
  protected $SampleTask2;

  const USER_CURRENT  = '18881701';
  const USER_OTHER    = '16778243';

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    
    //$this->object = new cliView;
    
    $this->SampleTask = new taskModel();
    $this->SampleTask->Title        = 'The quick brown fox jumped over the lazy'
            . ' dogs and foobared the whole thing.';
    $this->SampleTask->UpdatedDate  = '2016-09-03 04:45:21';
    $this->SampleTask->CreatedDate  = '2016-09-03 04:45:21';
    $this->SampleTask->CreatedBy    = self::USER_CURRENT;
    $this->SampleTask->UpdatedBy    = self::USER_CURRENT;
    
    $this->SampleTask2 = new taskModel();
    $this->SampleTask2->Title       = 'The quick brown fox jumped over the lazy'
            . ' dogs and foobared.';
    $this->SampleTask2->UpdatedDate  = '2016-09-03 05:33:14';
    $this->SampleTask2->CreatedDate  = '2016-09-03 04:45:21';
    $this->SampleTask2->CreatedBy    = self::USER_OTHER;
    $this->SampleTask2->UpdatedBy    = self::USER_CURRENT;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * @covers emeraldinspirations\TaskListDemo\task\cliListView::output
   * @todo   Implement testOutput().
   */
  public function testOutput() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }
  /**
   * @covers emeraldinspirations\TaskListDemo\task\cliListView::renderIndicatorModified
   */
  public function testRenderIndicatorModified() {
    $this->assertEquals(
            ' ',
            cliListView::renderIndicatorModified(
                    $this->SampleTask, self::USER_CURRENT),
            'Not Modified not rendered correctly'
    );
    
    $this->assertEquals(
            "\033[32m.",
            cliListView::renderIndicatorModified(
                    $this->SampleTask2, self::USER_CURRENT),
            'Self-Modified not rendered correctly'
    );
    
    $this->assertEquals(
            "\033[31m!",
            cliListView::renderIndicatorModified(
                    $this->SampleTask2, self::USER_OTHER),
            'Others-Modified not rendered correctly'
    );
  }

  /**
   * @covers emeraldinspirations\TaskListDemo\task\cliListView::renderTitle
   */
  public function testRenderTitle() {
    $this->assertEquals(
            "\033[37mThe quick brown fox jumped over the lazy dogs and foobar...",
            cliListView::renderTitle($this->SampleTask),
            'Truncated title not rendered correctly'
    );
    
    $this->assertEquals(
            "\033[37mThe quick brown fox jumped over the lazy dogs and foobared.",
            cliListView::renderTitle($this->SampleTask2),
            'Standard title not rendered correctly'
    );
  }

  /**
   * @covers emeraldinspirations\TaskListDemo\task\cliListView::renderModDate
   */
  public function testRenderModDate() {
    $this->assertEquals(
            "\033[36m2016-09-03",
            cliListView::renderModDate($this->SampleTask),
            'Modified Date not rendered correctly'
    );
  }

}