<?php

namespace SnSDev\TaskListDemo;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-01 at 00:49:46.
 */
class taskTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var task
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    //$this->object = new task;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }
  
  public function test() {
    echo "\n".sha1('This is a test')."\n";
    echo "\n".sha1('This is a test')."\n";
    echo "\n".  strlen(sha1('This is a test'))."\n";
  }

}
